version: '3.7'
services:
  lx-starter:
    container_name: lxstarter
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start
    volumes:
      - ./:/app
      - /app/node_modules
    tty: true
    ports:
      - 3030:3030
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
